name: janus_client
description: A feature rich Janus Webrtc package
version: 2.3.10
homepage: https://github.com/shivanshtalwar0/flutter_janus_client

environment:
  sdk: ">=2.15.0 <3.22.1"
  flutter: ">=1.10.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

dependencies:
  flutter_web_plugins:
    sdk: flutter
  flutter:
    sdk: flutter
  flutter_webrtc: ^0.14.1
  path_provider: ^2.1.5
  http: ^1.4.0
  web_socket_channel: ^3.0.3
  uuid: ^4.5.1
  logging: ^1.3.0
  dartdoc: ^8.3.4